#!/bin/sh
set -e

lb config noauto \
	--distribution trixie \
	--architectures amd64 \
	--archive-areas 'main non-free-firmware' \
	--binary-images iso-hybrid \
	--debian-installer live \
	--updates true \
	--security true \
	"${@}"
