#!/bin/sh
# Build the SWAT-OS ISO using the config tree in ./config, generated by ./auto/config.
set -e

cd "$(dirname "$0")/.."

./auto/config
sudo lb build

mkdir -p output
mv -f live-image-*.hybrid.iso "output/" 2>/dev/null || true
mv -f live-image-*.contents "output/" 2>/dev/null || true

echo "Build complete. ISO(s) in output/:"
ls -la output/*.iso 2>/dev/null || echo "(no ISO found - check the build log above for errors)"
